# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 43d8b3c91c250e33f3e25ba66335a9074ad7fd955038d6e794e6def341a6c485080bb942497d60997725b81d093890b021861f95af6b75f279991ab5dfd36c76

test:
  secret_key_base: 8d24a810c60523f9ceb826b59b574ddf26e1f0e5193e9b075753bad8960ffc4d90a6b163045ab405a62e80e7f9c4b76918d710feca088af7cc9fefe0396fde10

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
